"""Draw the English font for Evangelion 64.

Renders Latin letters from an open-licensed TrueType font into the game's
glyph format (24x24, 4 bits per pixel: 0 = see-through, 1 = dark outline,
2..15 = letter brightness) and assigns them to font slots.

Writes:
  games\\eva64\\work\\font\\font_en.json      glyph pixels and widths per slot (read by build.py)
  games\\eva64\\work\\font\\preview.png       sample lines as the game would lay them out
  games\\eva64\\scripts\\charmap_en.txt       the character table for English text

Run it through makefont.bat.
"""
import json

from PIL import Image, ImageDraw, ImageFont

import eva64lib as L
import extract as X

FONT_FILE = L.WORKSPACE / "tools" / "fonts" / "NotoSerif-VF.ttf"
FONT_SIZE = 16
FONT_WEIGHT = 700      # bold, so the smaller letters stay readable
FONT_WIDTH = 62.5      # percent of normal width (the font's narrowest)
BASELINE = 19          # pixel row the letters sit on
LEFT = 1               # room for the outline on the left
SPACE_WIDTH = 5
OUT = L.WORK_DIR / "font"

# slot -> character. Slots not listed keep their Japanese glyph.
ASSIGN = {1: ",", 2: ".", 4: ":", 5: "?", 6: "!"}
ASSIGN.update({11 + i: c for i, c in enumerate("0123456789")})
ASSIGN.update({21 + i: c for i, c in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ")})
ASSIGN.update({47 + i: c for i, c in enumerate("abcdefghijklmnopqrstuvwxyz")})
ASSIGN.update({73 + i: c for i, c in enumerate("'\"-;()/&")})

PREVIEW = [
    "Fifteen years since Second Impact.",
    "An unknown object nears the shore.",
    "\"It's been fifteen years, hasn't it?\"",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "abcdefghijklmnopqrstuvwxyz 0123456789",
    "Target: 3rd Angel, Sachiel (EVA-01)",
]


def load_font(size=FONT_SIZE, weight=FONT_WEIGHT, width=FONT_WIDTH):
    font = ImageFont.truetype(str(FONT_FILE), size)
    axes = font.get_variation_axes()
    values = []
    for axis in axes:
        name = axis["name"]
        name = name.decode() if isinstance(name, bytes) else name
        if name.lower().startswith("weight"):
            values.append(weight)
        elif name.lower().startswith("width"):
            values.append(width)
        else:
            values.append(axis["default"])
    font.set_variation_by_axes(values)
    return font


def render(font, ch):
    """Return (rows of 24 values 0..15, width in pixels)."""
    img = Image.new("L", (48, 24), 0)
    ImageDraw.Draw(img).text((LEFT, BASELINE), ch, font=font, fill=255, anchor="ls")
    advance = font.getlength(ch)
    px = [[0] * 24 for _ in range(24)]
    for y in range(24):
        for x in range(24):
            v = round(img.getpixel((x, y)) * 15 / 255)
            px[y][x] = v if v >= 2 else 0
    if any(img.getpixel((x, y)) for x in range(24, 48) for y in range(24)):
        raise SystemExit(f"glyph {ch!r} is wider than the 24 pixel cell")
    # dark outline: any empty pixel close to a bright one
    solid = [(x, y) for y in range(24) for x in range(24) if px[y][x] >= 5]
    for sx, sy in solid:
        for dy in range(-2, 3):
            for dx in range(-2, 3):
                if dx * dx + dy * dy > 2:
                    continue
                x, y = sx + dx, sy + dy
                if 0 <= x < 24 and 0 <= y < 24 and px[y][x] == 0:
                    px[y][x] = 1
    width = min(24, round(advance) + LEFT)
    return px, width


def pack(px):
    out = bytearray()
    for row in px:
        for x in range(0, 24, 2):
            out.append((row[x] << 4) | row[x + 1])
    return bytes(out)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    font = load_font()
    rom = L.find_rom().read_bytes()
    tokens = X.load_charmap()
    widths = list(rom[L.WIDTH_TABLE:L.WIDTH_TABLE + L.GLYPH_COUNT])
    glyphs = {}
    data = {"0": {"char": " ", "width": SPACE_WIDTH, "pixels": None}}
    widths[0] = SPACE_WIDTH
    for slot, ch in sorted(ASSIGN.items()):
        px, width = render(font, ch)
        glyphs[ch] = (px, width)
        widths[slot] = width
        data[str(slot)] = {"char": ch, "width": width, "pixels": pack(px).hex()}
    (OUT / "font_en.json").write_text(json.dumps(data, indent=0), encoding="utf-8")

    # Character table: replaced slots take the new character. A Japanese glyph whose
    # token collides with a new character is renamed {jpN} so every token stays unique.
    new_tokens = list(tokens)
    taken = set(ASSIGN.values())
    for i, t in enumerate(new_tokens):
        if i in ASSIGN:
            new_tokens[i] = ASSIGN[i]
        elif t in taken:
            new_tokens[i] = f"{{jp{i}}}"
    if len(set(new_tokens)) != L.GLYPH_COUNT:
        raise SystemExit("character table has duplicate entries")
    lines = [
        "# Evangelion 64 English character table. Generated by tools\\eva64\\makefont.py; do not edit by hand.",
        "# Same layout as charmap_jp.txt: 538 entries in font order, 16 per line. Code = position + 0x10.",
    ]
    lines += [" ".join(new_tokens[i:i + 16]) for i in range(0, L.GLYPH_COUNT, 16)]
    (L.GAME_DIR / "scripts" / "charmap_en.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Preview: lay out sample lines the way the game does (cell drawn at pen, pen += width).
    scale = 3
    line_h = 26
    canvas = Image.new("L", (288, line_h * len(PREVIEW)), 90)
    for n, text in enumerate(PREVIEW):
        pen = 0
        for ch in text:
            if ch == " ":
                pen += SPACE_WIDTH
                continue
            px, width = glyphs[ch]
            for y in range(24):
                for x in range(24):
                    v = px[y][x]
                    if v and pen + x < 288:
                        canvas.putpixel((pen + x, n * line_h + y), 0 if v == 1 else v * 17)
            pen += width
        print(f"{pen:4d} px  {text}")
    canvas.resize((288 * scale, canvas.height * scale), Image.NEAREST).save(OUT / "preview.png")
    letters = [glyphs[c][1] for c in "abcdefghijklmnopqrstuvwxyz"]
    print(f"{len(ASSIGN)} glyphs drawn; average lowercase width {sum(letters) / len(letters):.1f} px")
    print(f"wrote {OUT / 'font_en.json'}, {OUT / 'preview.png'} and scripts\\charmap_en.txt")


if __name__ == "__main__":
    main()
